### ISSUE TITLE
Problem with testing

### ISSUE THREAD

**Issue by bei21** [Zjut-MultimediaPlus/DADH#5]
Hi,

I came across an error when running "python main.py test --flag 'nus' --bit 16" as below: 

RuntimeError: Error(s) in loading state_dict for GEN:
        Missing key(s) in state_dict: "image_module.3.weight", "image_module.3.bias", "image_module.4.running_mean", "image_module.4.running_var", "image_module.6.weight", "image_module.6.bias", "image_module.7.weight", "image_module.7.bias", "image_module.7.running_mean", "image_module.7.running_var", "text_module.3.weight", "text_module.3.bias", "text_module.4.running_mean", "text_module.4.running_var", "text_module.6.weight", "text_module.6.bias", "text_module.7.weight", "text_module.7.bias", "text_module.7.running_mean", "text_module.7.running_var".
        Unexpected key(s) in state_dict: "image_module.9.weight", "image_module.9.bias", "image_module.9.running_mean", "image_module.9.running_var", "image_module.9.num_batches_tracked", "image_module.5.weight", "image_module.5.bias", "image_module.5.running_mean", "image_module.5.running_var", "image_module.5.num_batches_tracked", "image_module.8.weight", "image_module.8.bias", "text_module.9.weight", "text_module.9.bias", "text_module.9.running_mean", "text_module.9.running_var", "text_module.9.num_batches_tracked", "text_module.5.weight", "text_module.5.bias", "text_module.5.running_mean", "text_module.5.running_var", "text_module.5.num_batches_tracked", "text_module.8.weight", "text_module.8.bias".
        size mismatch for image_module.4.weight: copying a param with shape torch.Size([4096, 8192]) from checkpoint, the shape in current model is torch.Size([4096]).
        size mismatch for text_module.4.weight: copying a param with shape torch.Size([4096, 8192]) from checkpoint, the shape in current model is torch.Size([4096]).

This occurs after I train with "bash run_nus.sh 16" script. 
Testing on "mir" dataset is OK without this error. 

Could you help to have a check?

Thanks.

**Comment by flyfish7** [comment]
In the training process on "nus", the dropout is used, so it is necessary to add "--dropout True" during the test.

**Comment by bei21** [comment]
Thanks, solved. 
Could you please add this to the readme?
